### ISSUE TITLE
Database reset doesn't reset ids

### ISSUE THREAD

**Issue by NovaGamma** [AbdullatifGhajar/software-testing-group-d#4]

**Comment by NovaGamma** [comment]
Maybe desired: resetting a database will clear the tables but not drop them, because the counter for the employees’ ids doesn’t reset

**Comment by NovaGamma** [comment]
Maybe desired: resetting a database will clear the tables but not drop them, because the counter for the employees’ ids doesn’t reset

**Comment by popolito1** [comment]
A.0.4 : not fixed

**Comment by popolito1** [comment]
Not a real issue => we saw with the teacher
